name: buildpaw
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.6 <4.0.0"

dependencies:
  cross_file: ^0.3.5+2
  cupertino_icons: 1.0.8
  desktop_drop: 0.7.0
  equatable: 2.0.7
  file_picker: 9.2.1
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.0
  flutter_localizations:
    sdk: flutter
  google_fonts: 6.2.1
  shared_preferences: 2.3.3
  slang: 4.12.1
  slang_flutter: 4.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: 9.0.0

flutter:
  uses-material-design: true
