import '../../domain/domain.dart';

/// Generates platform-specific Fastfile, Appfile, and .env.default from [PublishProfile].
/// Android config goes to android/fastlane/, iOS config to ios/fastlane/.
final class FastlaneConfigGenerator {
  /// Platform directory for Fastlane (android or ios).
  static String platformDirForTarget(PublishTarget target) {
    return switch (target) {
      PublishTarget.firebase => 'android',
      PublishTarget.googlePlay => 'android',
      PublishTarget.appStoreConnect => 'ios',
    };
  }

  /// Generates Android Fastfile (Firebase + Play Store lanes).
  static String generateAndroidFastfile(PublishProfile profile) {
    final buffer = StringBuffer();
    buffer
      ..writeln('# Auto-generated by BuildPaw. Edit as needed.')
      ..writeln('# See: https://docs.fastlane.tools')
      ..writeln()
      ..writeln('default_platform(:android)')
      ..writeln()
      ..writeln('platform :android do')
      ..writeln('  desc "Push a new build to Firebase App Distribution"')
      ..writeln('  lane :firebase do')
      ..writeln('    begin')
      ..writeln('      build_path = ENV["LAST_BUILD_PATH"]')
      ..writeln('      raise "LAST_BUILD_PATH required" if build_path.to_s.empty?')
      ..writeln('      path = Dir["#{build_path}/android/apk/*.apk"].first')
      ..writeln('      raise "No IPA/APK/AAB found in #{build_path}" if path.nil?')
      ..writeln('      opts = {')
      ..writeln('        app: ENV["FIREBASE_APP_ID"],')
      ..writeln('        firebase_cli_token: ENV["FIREBASE_TOKEN"],')
      ..writeln('        release_notes: ENV["RELEASE_NOTES"] || "",')
      ..writeln('        groups: (ENV["FIREBASE_GROUPS"] || "").strip,')
      ..writeln('        apk_path: path,')
      ..writeln('        android_artifact_type: "APK"')
      ..writeln('      }')
      ..writeln('      opts[:firebase_cli_path] = ENV["FIREBASE_CLI_PATH"] if ENV["FIREBASE_CLI_PATH"].to_s != ""')
      ..writeln('      firebase_app_distribution(opts)')
      ..writeln('    end')
      ..writeln('  end')
      ..writeln()
      ..writeln('  desc "Validate Play Store JSON key"')
      ..writeln('  lane :validate_play_store_json_file do')
      ..writeln('    begin')
      ..writeln('      json_key = ENV["GOOGLE_PLAY_JSON_KEY"]')
      ..writeln('      validate_play_store_json_key(json_key: json_key) if json_key.to_s != ""')
      ..writeln('    end')
      ..writeln('  end');

    for (final track in PlayTrack.values) {
      buffer
        ..writeln()
        ..writeln('  desc "Push a new build to Play Store ${track.value}"')
        ..writeln('  lane :play_${track.value} do')
        ..writeln('    begin')
        ..writeln('      build_path = ENV["LAST_BUILD_PATH"]')
        ..writeln('      raise "LAST_BUILD_PATH required" if build_path.to_s.empty?')
        ..writeln('      path = Dir["#{build_path}/android/aab/*.aab"].first')
        ..writeln('      raise "No AAB/APK found in #{build_path}" if path.nil?')
        ..writeln('      version_info = flutter_version() rescue {}')
        ..writeln('      version_name = ENV["VERSION_NAME"]')
        ..writeln(
          '      version_name = version_info["version_name"].to_s + "+" + version_info["version_code"].to_s if version_name.to_s.empty? && version_info.any?',
        )
        ..writeln('      upload_opts = {')
        ..writeln('        track: "${track.value}",')
        ..writeln('        aab: path,')
        ..writeln('        package_name: ENV["PACKAGE_NAME"],')
        ..writeln('        json_key: ENV["GOOGLE_PLAY_JSON_KEY"],')
        ..writeln('        skip_upload_metadata: true,')
        ..writeln('        skip_upload_images: true,')
        ..writeln('        skip_upload_screenshots: true')
        ..writeln('      }')
        ..writeln('      upload_opts[:version_name] = version_name if version_name.to_s != ""')
        ..writeln('      upload_to_play_store(upload_opts)')
        ..writeln('    end')
        ..writeln('  end');
    }
    buffer.writeln('end');
    return buffer.toString();
  }

  /// Generates iOS Fastfile (TestFlight lane).
  static String generateIosFastfile(PublishProfile profile) {
    return '''
# Auto-generated by BuildPaw. Edit as needed.
# See: https://docs.fastlane.tools
default_platform(:ios)


platform :ios do
  desc "Push a new build to TestFlight"
  lane :testflight do
    begin
      build_path = ENV["LAST_BUILD_PATH"]
      raise "LAST_BUILD_PATH required" if build_path.to_s.empty?
      ipa = Dir["#{build_path}/ios/*.ipa"].first
      raise "No IPA found in #{build_path}/ios" if ipa.nil?
      upload_to_testflight(ipa: ipa, skip_submission: true)
    end
  end
end
''';
  }

  /// Generates Android Appfile (Play Store config).
  static String generateAndroidAppfile(PublishProfile profile) {
    return '''
# Auto-generated by BuildPaw. Edit as needed.
# See: https://docs.fastlane.tools/advanced/Appfile/

  json_key_file(ENV["JSON_KEY_FILE"])
  package_name(ENV["PACKAGE_NAME"])
''';
  }

  /// Generates iOS Appfile (App Store Connect config).
  static String generateIosAppfile(PublishProfile profile) {
    return '''
# Auto-generated by BuildPaw. Edit as needed.
# See: https://docs.fastlane.tools/advanced/Appfile/

  app_identifier(ENV["APP_IDENTIFIER"])
  apple_id(ENV["FASTLANE_USER"])
  team_id(ENV["TEAM_ID"])
  itc_team_id(ENV["ITC_TEAM_ID"])
''';
  }

  /// Generates .env.default for Android.
  static String generateAndroidEnvDefault(PublishProfile profile) {
    return '''
# Auto-generated by BuildPaw. Copy to .env and fill in values.
# Fastlane loads .env automatically. Do NOT commit .env to git.

# --- Firebase App Distribution ---
FIREBASE_APP_ID=
FIREBASE_TOKEN=
# FIREBASE_CLI_PATH=/usr/local/bin/firebase

# --- Google Play ---
PACKAGE_NAME=
GOOGLE_PLAY_JSON_KEY=
JSON_KEY_FILE=
''';
  }

  /// Gemfile content for Ruby/Bundler. Create in platform dir (android/ or ios/).
  static const String gemfileContent = '''
source "https://rubygems.org"

gem "fastlane", "~> 2.230.0"

# Ruby 3.4'te default gem olmayanlar için uyarıyı susturur
gem "abbrev", "~> 0.1", require: false
gem "logger"
gem "mutex_m"
gem "csv"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
''';

  /// Pluginfile content for Fastlane plugins. Create in platform/fastlane/Pluginfile.
  static const String pluginfileContent = '''
# Fastlane plugins
gem 'fastlane-plugin-firebase_app_distribution'
gem 'fastlane-plugin-flutter_version'
''';

  /// Generates .env.default for iOS.
  static String generateIosEnvDefault(PublishProfile profile) {
    return '''
# Auto-generated by BuildPaw. Copy to .env and fill in values.
# Fastlane loads .env automatically. Do NOT commit .env to git.

# --- App Store Connect (Apple ID auth) ---
FASTLANE_USER=
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=
APP_IDENTIFIER=
TEAM_ID=
ITC_TEAM_ID=

# --- App Store Connect (API Key auth, alternative) ---
ASC_KEY_ID=
ASC_ISSUER_ID=
ASC_KEY_PATH=
''';
  }
}
